// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZ1crISefAA8BQexbNV-UD7m77JwYd-U',
    appId: '1:139310689865:web:edd54cacec322a5b8c9998',
    messagingSenderId: '139310689865',
    projectId: 'puc-quest-rpg',
    authDomain: 'puc-quest-rpg.firebaseapp.com',
    storageBucket: 'puc-quest-rpg.firebasestorage.app',
    measurementId: 'G-PM7412J17Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsC-RnGYVLd20SYuCEJJ9IPwvUhA2nY_s',
    appId: '1:139310689865:android:94acd2f3b9b387178c9998',
    messagingSenderId: '139310689865',
    projectId: 'puc-quest-rpg',
    storageBucket: 'puc-quest-rpg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_GhigsfIQMZmdjAdsMZkXd-uXJ6XTIT0',
    appId: '1:139310689865:ios:1175ac801849bc8a8c9998',
    messagingSenderId: '139310689865',
    projectId: 'puc-quest-rpg',
    storageBucket: 'puc-quest-rpg.firebasestorage.app',
    iosClientId: '139310689865-o4puc0469vek6ab1a6qoqhv3o3poj3bk.apps.googleusercontent.com',
    iosBundleId: 'com.company.PucQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQZ1crISefAA8BQexbNV-UD7m77JwYd-U',
    appId: '1:139310689865:web:edd54cacec322a5b8c9998',
    messagingSenderId: '139310689865',
    projectId: 'puc-quest-rpg',
    authDomain: 'puc-quest-rpg.firebaseapp.com',
    storageBucket: 'puc-quest-rpg.firebasestorage.app',
    measurementId: 'G-PM7412J17Q',
  );
}
