// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ehP3tX5GMxXcGSeM5zV9wPOnK_PDwP8',
    appId: '1:106292251398:web:c086321a53cef4864e6c87',
    messagingSenderId: '106292251398',
    projectId: 'pi-projeto-e15f1',
    authDomain: 'pi-projeto-e15f1.firebaseapp.com',
    storageBucket: 'pi-projeto-e15f1.firebasestorage.app',
    measurementId: 'G-CG19D17W76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEu0FTSgoSnIx0_RvhSC4dIOyg70_2yfU',
    appId: '1:106292251398:android:8676b8443ae375174e6c87',
    messagingSenderId: '106292251398',
    projectId: 'pi-projeto-e15f1',
    storageBucket: 'pi-projeto-e15f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjCvimbXbrXj5WMiXqSDydbeudmwN0CKo',
    appId: '1:106292251398:ios:613019d06e4c950c4e6c87',
    messagingSenderId: '106292251398',
    projectId: 'pi-projeto-e15f1',
    storageBucket: 'pi-projeto-e15f1.firebasestorage.app',
    iosBundleId: 'com.example.pirpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ehP3tX5GMxXcGSeM5zV9wPOnK_PDwP8',
    appId: '1:106292251398:web:5b1634a9779cc7814e6c87',
    messagingSenderId: '106292251398',
    projectId: 'pi-projeto-e15f1',
    authDomain: 'pi-projeto-e15f1.firebaseapp.com',
    storageBucket: 'pi-projeto-e15f1.firebasestorage.app',
    measurementId: 'G-ZN2CSRS5ED',
  );
}
