name: Build and Release APK

on:
  push:
    tags:
      - 'v*' # Dispara automaticamente quando você criar uma tag (ex: git tag v1.0.0)
  workflow_dispatch: # Permite que você clique em "Run workflow" manualmente lá na aba Actions do GitHub

jobs:
  build:
    name: Build APK and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # O Java 17 é recomendado pelas versões mais recentes do Flutter

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
          name: ${{ github.ref_type == 'tag' && format('Release {0}', github.ref_name) || 'Latest Build' }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
